name: mkpass
version: '2.0.8'
summary: Simple secure password generator
description: |
  MKPASS is a command line password generator.  There are several options
  that allow control of the password length as well as an option to
  include special symbols.  Running without options defaults to producing
  a 30 character password with special characters.
  Please let me know if you have suggestions.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict  # use 'strict' once you have the right plugs and slots
base: core18

# Enable faszter LZO compression
compression: lzo

apps:
  mkpass:
    command: bin/java -Djava.security.egd=file:/dev/./urandom -Djava.util.prefs.userRoot="$SNAP_USER_DATA" -jar $SNAP/jar/mkpass.jar

parts:
  mkpqss:
    plugin: maven
    source: https://github.com/frossm/mkpass.git
    source-branch: master
    source-type: git
    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs
